/* =========================
   dados.js
   Módulo centralizado de dados do dashboard.
   Importado pelo arquivo "app.js".
========================= */

// --- Panorama geral (KPIs do topo)
export const panorama = [
  {
    valor: "708 mil",
    label: "Profissionais na região",
    sublabel: "Perfis ativos no LinkedIn",
    icon: "fa-solid fa-users",
  },
  {
    valor: "65.542",
    label: "Mudanças de emprego",
    sublabel: "Trocas nos últimos 12 meses",
    icon: "fa-solid fa-arrows-rotate",
  },
  {
    valor: "5.110",
    label: "Anúncios de vaga",
    sublabel: "Média diária (últimos 30 dias)",
    icon: "fa-solid fa-briefcase",
  },
  {
    valor: "685",
    label: "Talentos engajados",
    sublabel: "Interagiram com a organização",
    icon: "fa-solid fa-paper-plane",
  },
  {
    valor: "48/52%",
    label: "Feminino / Masculino",
    sublabel: "Desigualdade de gênero: 4%",
    icon: "fa-solid fa-venus-mars",
  },
  {
    valor: "UNICAMP",
    label: "Principal empregador",
    sublabel: "6.703 profissionais",
    icon: "fa-solid fa-building-columns",
  },
];

// --- Setores: demanda
export const setoresDemanda = [
  {
    setor: "Comércio varejista",
    demanda: "Moderada",
    vagas: 325,
    crescimento: -2,
  },
  { setor: "TI e Serviços", demanda: "Muito alta", vagas: 325, crescimento: 0 },
  { setor: "Saúde", demanda: "Moderada", vagas: 93, crescimento: -1 },
  {
    setor: "Serviços prediais",
    demanda: "Nível baixo",
    vagas: 48,
    crescimento: -1,
  },
  { setor: "Adm. pública", demanda: "Nível baixo", vagas: "—", crescimento: 0 },
  { setor: "Alimentação", demanda: "Alto", vagas: 64, crescimento: -1 },
];

// --- Setores: profissionais
export const setoresProfissionais = [
  { setor: "Comércio varejista", profissionais: 35943 },
  { setor: "TI e Serviços", profissionais: 28000 },
  { setor: "Saúde", profissionais: 25000 },
  { setor: "Educação", profissionais: 20000 },
  { setor: "Manufatura", profissionais: 18000 },
  { setor: "Serviços Financeiros", profissionais: 15000 },
];

// --- Top empresas por profissionais
export const topEmpresasProfissionais = [
  { empresa: "UNICAMP", profissionais: 6703 },
  { empresa: "Bosch", profissionais: 4500 },
  { empresa: "IBM", profissionais: 3800 },
  { empresa: "CPFL Energia", profissionais: 3200 },
  { empresa: "Samsung", profissionais: 2900 },
  { empresa: "Hospital Vera Cruz", profissionais: 2500 },
];

// --- Rotatividade e crescimento por empresa
export const rotatividadeCrescimento = [
  { empresa: "UNICAMP", rotatividade: 12, crescimento: 5 },
  { empresa: "Bosch", rotatividade: 15, crescimento: 3 },
  { empresa: "IBM", rotatividade: 10, crescimento: 7 },
  { empresa: "CPFL Energia", rotatividade: 18, crescimento: 2 },
  { empresa: "Samsung", rotatividade: 14, crescimento: 4 },
  { empresa: "Hospital Vera Cruz", rotatividade: 20, crescimento: 1 },
];

// --- Gênero nos principais cargos
export const generoPrincipaisCargos = [
  { cargo: "Assist. administrativo", feminino: 73, masculino: 27 },
  { cargo: "Vendedor", feminino: 52, masculino: 48 },
  { cargo: "Professor", feminino: 64, masculino: 36 },
  { cargo: "Proprietário", feminino: 34, masculino: 66 },
  { cargo: "Gerente", feminino: 39, masculino: 61 },
  { cargo: "Advogado", feminino: 54, masculino: 46 },
  { cargo: "Caixa", feminino: 86, masculino: 14 },
  { cargo: "Técnico de enf.", feminino: 82, masculino: 18 },
  { cargo: "Diretor", feminino: 22, masculino: 78 },
  { cargo: "Recepcionista", feminino: 91, masculino: 9 },
];

// --- Competências comuns
export const competenciasComuns = [
  { competencia: "Habilidades analíticas", count: 70 },
  { competencia: "Análise de dados", count: 65 },
  { competencia: "Ciclo PDCA", count: 58 },
  { competencia: "Linhas de produção", count: 50 },
  { competencia: "5S", count: 45 },
  { competencia: "Sistemas operacionais", count: 40 },
  { competencia: "Produtos SAP", count: 35 },
  { competencia: "Gestão de vendas", count: 30 },
  { competencia: "Análise financeira", count: 28 },
  { competencia: "Melhoria contínua", count: 25 },
];

// --- Competências em crescimento
export const competenciasCrescimento = [
  { competencia: "Corte em cubos", crescimento: 22 },
  { competencia: "Ajuste de seguro", crescimento: 15 },
  { competencia: "Relatórios KPI", crescimento: 14 },
  { competencia: "Processos adm.", crescimento: 13 },
  { competencia: "Microsoft PowerApps", crescimento: 12 },
  { competencia: "Implementação de KPI", crescimento: 11 },
  { competencia: "CRM", crescimento: 10 },
  { competencia: "Comercial", crescimento: 10 },
  { competencia: "Satisfação do cliente", crescimento: 10 },
];

// --- Nível de formação
export const nivelFormacao = [
  { nivel: "Bacharelado", valor: 50 },
  { nivel: "MBA", valor: 19 },
  { nivel: "Mestrado", valor: 21 },
  { nivel: "Doutorado", valor: 5 },
  { nivel: "Nível técnico", valor: 5 },
];

// --- Áreas de estudo (gráfico)
export const areasEstudo = [
  { area: "Administração", valor: 28000 },
  { area: "Direito", valor: 23000 },
  { area: "Adm. e Negócios", valor: 19000 },
  { area: "RH", valor: 16000 },
  { area: "Logística", valor: 13000 },
  { area: "Marketing", valor: 12500 },
  { area: "TI", valor: 12000 },
  { area: "Educação", valor: 10000 },
  { area: "Ciência Comp.", valor: 9500 },
  { area: "Psicologia", valor: 9000 },
];

// --- Instituições de ensino
export const instituicoes = [
  { nome: "PUC-Campinas", profissionais: 44269, recem: 6091 },
  { nome: "UNICAMP", profissionais: 40467, recem: 8825 },
  { nome: "UNIP", profissionais: 34683, recem: 5752 },
  { nome: "Anhanguera", profissionais: 32971, recem: 7480 },
  { nome: "FGV", profissionais: 13464, recem: 2044 },
  { nome: "USF", profissionais: 10992, recem: 2516 },
];

// --- Fluxo por localidade
export const fluxoLocalidade = [
  { local: "São Paulo", saldo: 1500 },
  { local: "Campinas", saldo: 0 },
  { local: "Ribeirão Preto", saldo: -300 },
  { local: "Jundiaí", saldo: 200 },
  { local: "Sorocaba", saldo: -150 },
];

// --- Fluxo por setor
export const fluxoSetor = [
  { setor: "TI e Serviços", saldo: 400 },
  { setor: "Comércio varejista", saldo: 0 },
  { setor: "Saúde", saldo: -200 },
  { setor: "Manufatura", saldo: 100 },
  { setor: "Serviços Prediais", saldo: -50 },
];

// --- Engajamento
export const engajamento = [
  { label: "Total engajados", valor: 685 },
  { label: "Visitaram Company Page", valor: 274 },
  { label: "Novos seguidores", valor: 213 },
  { label: "Interagiram com posts", valor: 300 },
  { label: "Visualizaram vagas anunciadas", valor: 3 },
];

// --- Propostas de valor (EVP)
export const propostasValor = [
  { fator: "Salário e Benefícios", consenso: 85 },
  { fator: "Equilíbrio Vida/Trabalho", consenso: 78 },
  { fator: "Oportunidades de Crescimento", consenso: 70 },
  { fator: "Cultura da Empresa", consenso: 65 },
  { fator: "Impacto do Trabalho", consenso: 60 },
];

// --- Perfis em destaque
export const perfis = [
  {
    nome: "Douglas Pacifico",
    cargo: "Diretor – Facility Management e Real Estate – América Latina",
    local: "Brasil",
    empresa: "Bosch",
  },
  {
    nome: "Pedro Martini",
    cargo: "Diretor de Tecnologia | CIO | Inovação | Transformação Digital",
    local: "Campinas, SP",
    empresa: "Cotrijal Cooperativa",
  },
  {
    nome: "Ricardo Bonassi, MBA",
    cargo: "Sr. Director of Business Development – Brazil, LATAM",
    local: "Campinas, SP",
    empresa: "nativeMsg",
  },
  {
    nome: "Luciano Benato",
    cargo: "CTO | Governo & Saúde | Microsoft · AWS · IBM | PMP",
    local: "Brasil",
    empresa: "BSM Group",
  },
  {
    nome: "Rodrigo Zenji Hida",
    cargo: "Head of Software Engineering",
    local: "Campinas e Região",
    empresa: "Superlógica",
  },
  {
    nome: "Leonardo Zeferino",
    cargo: "Acelerando negócios com IA | Agentes de IA | Founder na FAST",
    local: "Campinas, SP",
    empresa: "FAST Builders",
  },
  {
    nome: "Juliana Barbosa",
    cargo: "Head of AI Platform | Product",
    local: "Campinas, SP",
    empresa: "Cayena",
  },
  {
    nome: "Carlos A. Baldessini",
    cargo: "Executivo RH | Gerente Recursos Humanos | Business Partner",
    local: "Campinas, SP",
    empresa: "Aeroportos Brasil Viracopos",
  },
];

/* ===== Talent Insights (consolidado) ===== */
export const talentInsightsData = {
  kpis: [
    {
      label: "Competências mapeadas",
      valor: 100,
      sufixo: "",
      nota: "Total geral",
      icon: "fa-solid fa-layer-group",
    },
    {
      label: "Vagas totais",
      valor: 4046,
      sufixo: "",
      nota: "Carga atual",
      icon: "fa-solid fa-briefcase",
    },
    {
      label: "Talentos mapeados",
      valor: 170,
      sufixo: "",
      nota: "Base interna",
      icon: "fa-solid fa-star",
    },
    {
      label: "Gap de gênero",
      valor: 26.0,
      sufixo: "%",
      nota: "Diferença média F/M",
      isPercent: true,
      icon: "fa-solid fa-venus-mars",
    },
  ],
  insights: [
    {
      title: "Maior demanda bruta",
      text: "Satisfação do cliente lidera em anúncios de vaga, com 480 registros na carga atual.",
      color: "#1d4ed8",
    },
    {
      title: "Maior gap demanda x talentos internos",
      text: "Satisfação do cliente tem gap de 480, combinando alta demanda com baixa presença interna mapeada.",
      color: "#1f6feb",
    },
    {
      title: "Maior desequilíbrio de gênero",
      text: "JavaScript apresenta diferença de 76% entre os percentuais feminino e masculino.",
      color: "#7c3aed",
    },
    {
      title: "Pipeline formativo",
      text: "Data Science possui 50,7% de recém-formados entre os profissionais da área.",
      color: "#059669",
    },
  ],
  miniChart: {
    labels: [
      "Satisfação do cliente",
      "Planejamento",
      "Power BI",
      "Comunicação",
      "Excel",
      "Análise de dados",
    ],
    vagas: [480, 420, 310, 250, 220, 190],
  },
};

export const talentKpis = [
  {
    value: "100",
    label: "Competências mapeadas",
    subtitle: "Total geral",
    icon: "fa-solid fa-list-check",
    color: "#0ea5e9",
  },
  {
    value: "4.046",
    label: "Vagas totais",
    subtitle: "Carga atual",
    icon: "fa-solid fa-briefcase",
    color: "#f59e0b",
  },
  {
    value: "170",
    label: "Talentos mapeados",
    subtitle: "Base interna",
    icon: "fa-solid fa-star",
    color: "#3b82f6",
  },
  {
    value: "26,0%",
    label: "Gap de gênero",
    subtitle: "Diferença média F/M",
    icon: "fa-solid fa-venus-mars",
    color: "#ec4899",
  },
];

/* ===== Competências - Ranking Geral (dados mockados da tabela do PDF) ===== */
export const competenciasRanking = [
  {
    rank: 1,
    competencia: "Habilidades analíticas",
    profissionais: 15214,
    pctTotal: 5.25,
    vagas: 72,
    talentosInternos: 6,
    gap: 66,
    vagas1000: 4.7,
    feminino: 46,
    masculino: 54,
  },
  {
    rank: 2,
    competencia: "Análise de dados",
    profissionais: 13311,
    pctTotal: 4.6,
    vagas: 1,
    talentosInternos: 4,
    gap: -3,
    vagas1000: 0.1,
    feminino: 46,
    masculino: 54,
  },
  {
    rank: 3,
    competencia: "Gestão de vendas",
    profissionais: 9735,
    pctTotal: 3.36,
    vagas: 7,
    talentosInternos: 1,
    gap: 6,
    vagas1000: 0.7,
    feminino: 34,
    masculino: 66,
  },
  {
    rank: 4,
    competencia: "Análise financeira",
    profissionais: 9194,
    pctTotal: 3.17,
    vagas: 3,
    talentosInternos: 4,
    gap: -1,
    vagas1000: 0.3,
    feminino: 49,
    masculino: 51,
  },
  {
    rank: 5,
    competencia: "Planejamento empresarial",
    profissionais: 8459,
    pctTotal: 2.92,
    vagas: 7,
    talentosInternos: 6,
    gap: 1,
    vagas1000: 0.8,
    feminino: 33,
    masculino: 67,
  },
  {
    rank: 6,
    competencia: "Linhas de produção",
    profissionais: 7823,
    pctTotal: 2.7,
    vagas: 29,
    talentosInternos: 1,
    gap: 28,
    vagas1000: 3.7,
    feminino: 38,
    masculino: 62,
  },
  {
    rank: 7,
    competencia: "Sistemas operacionais",
    profissionais: 7615,
    pctTotal: 2.63,
    vagas: 70,
    talentosInternos: 7,
    gap: 63,
    vagas1000: 9.2,
    feminino: 34,
    masculino: 66,
  },
  {
    rank: 8,
    competencia: "Comercial",
    profissionais: 7523,
    pctTotal: 2.6,
    vagas: 159,
    talentosInternos: 1,
    gap: 158,
    vagas1000: 21.1,
    feminino: 35,
    masculino: 65,
  },
  {
    rank: 9,
    competencia: "Suporte administrativo",
    profissionais: 7509,
    pctTotal: 2.59,
    vagas: 17,
    talentosInternos: 2,
    gap: 15,
    vagas1000: 2.3,
    feminino: 67,
    masculino: 33,
  },
  {
    rank: 10,
    competencia: "Ciclo PDCA",
    profissionais: 7314,
    pctTotal: 2.53,
    vagas: 4,
    talentosInternos: 5,
    gap: -1,
    vagas1000: 0.5,
    feminino: 29,
    masculino: 71,
  },
  {
    rank: 11,
    competencia: "Sistemas operacionais (variação)",
    profissionais: 7182,
    pctTotal: 2.48,
    vagas: 0,
    talentosInternos: 7,
    gap: -7,
    vagas1000: 0.0,
    feminino: 34,
    masculino: 66,
  },
  {
    rank: 12,
    competencia: "Análise de negócios",
    profissionais: 7050,
    pctTotal: 2.43,
    vagas: 1,
    talentosInternos: 0,
    gap: 1,
    vagas1000: 0.1,
    feminino: 41,
    masculino: 59,
  },
  {
    rank: 13,
    competencia: "Capacidade analítica",
    profissionais: 6997,
    pctTotal: 2.42,
    vagas: 0,
    talentosInternos: 2,
    gap: -2,
    vagas1000: 0.0,
    feminino: 46,
    masculino: 54,
  },
  {
    rank: 14,
    competencia: "Contas a pagar",
    profissionais: 6889,
    pctTotal: 2.38,
    vagas: 61,
    talentosInternos: 1,
    gap: 60,
    vagas1000: 8.9,
    feminino: 67,
    masculino: 33,
  },
  {
    rank: 15,
    competencia: "Gestão de relacionamento com o cliente (CRM)",
    profissionais: 6315,
    pctTotal: 2.18,
    vagas: 157,
    talentosInternos: 0,
    gap: 157,
    vagas1000: 24.9,
    feminino: 46,
    masculino: 54,
  },
  {
    rank: 16,
    competencia: "AutoCAD",
    profissionais: 5959,
    pctTotal: 2.06,
    vagas: 1,
    talentosInternos: 5,
    gap: -4,
    vagas1000: 0.2,
    feminino: 33,
    masculino: 67,
  },
  {
    rank: 17,
    competencia: "Finanças",
    profissionais: 5949,
    pctTotal: 2.05,
    vagas: 216,
    talentosInternos: 3,
    gap: 213,
    vagas1000: 36.3,
    feminino: 48,
    masculino: 52,
  },
  {
    rank: 18,
    competencia: "Adobe Photoshop",
    profissionais: 5784,
    pctTotal: 2.0,
    vagas: 7,
    talentosInternos: 3,
    gap: 4,
    vagas1000: 1.2,
    feminino: 41,
    masculino: 59,
  },
  {
    rank: 19,
    competencia: "Vendas a varejo",
    profissionais: 5665,
    pctTotal: 1.96,
    vagas: 0,
    talentosInternos: 0,
    gap: 0,
    vagas1000: 0.0,
    feminino: 53,
    masculino: 47,
  },
  {
    rank: 20,
    competencia: "Relacionamentos interpessoais",
    profissionais: 5664,
    pctTotal: 1.96,
    vagas: 0,
    talentosInternos: 2,
    gap: -2,
    vagas1000: 0.0,
    feminino: 52,
    masculino: 48,
  },
  {
    rank: 21,
    competencia: "Relacionamento com clientes",
    profissionais: 5534,
    pctTotal: 1.91,
    vagas: 5,
    talentosInternos: 1,
    gap: 4,
    vagas1000: 0.9,
    feminino: 51,
    masculino: 49,
  },
  {
    rank: 22,
    competencia: "Recursos humanos (RH)",
    profissionais: 5452,
    pctTotal: 1.88,
    vagas: 116,
    talentosInternos: 6,
    gap: 110,
    vagas1000: 21.3,
    feminino: 69,
    masculino: 31,
  },
  {
    rank: 23,
    competencia: "Produtos SAP",
    profissionais: 5204,
    pctTotal: 1.8,
    vagas: 23,
    talentosInternos: 3,
    gap: 20,
    vagas1000: 4.4,
    feminino: 35,
    masculino: 65,
  },
  {
    rank: 24,
    competencia: "Gestão logística",
    profissionais: 5074,
    pctTotal: 1.75,
    vagas: 92,
    talentosInternos: 2,
    gap: 90,
    vagas1000: 18.1,
    feminino: 27,
    masculino: 73,
  },
  {
    rank: 25,
    competencia: "Gestão de pessoas",
    profissionais: 5023,
    pctTotal: 1.73,
    vagas: 3,
    talentosInternos: 3,
    gap: 0,
    vagas1000: 0.6,
    feminino: 43,
    masculino: 57,
  },
  {
    rank: 26,
    competencia: "Contas a receber",
    profissionais: 5020,
    pctTotal: 1.73,
    vagas: 81,
    talentosInternos: 0,
    gap: 81,
    vagas1000: 16.1,
    feminino: 66,
    masculino: 34,
  },
  {
    rank: 27,
    competencia: "Suporte ao cliente",
    profissionais: 4871,
    pctTotal: 1.68,
    vagas: 6,
    talentosInternos: 0,
    gap: 6,
    vagas1000: 1.2,
    feminino: 57,
    masculino: 43,
  },
  {
    rank: 28,
    competencia: "Processo de faturamento",
    profissionais: 4854,
    pctTotal: 1.68,
    vagas: 0,
    talentosInternos: 1,
    gap: -1,
    vagas1000: 0.0,
    feminino: 66,
    masculino: 34,
  },
  {
    rank: 29,
    competencia: "ERP (Planejamento de recursos empresariais)",
    profissionais: 4833,
    pctTotal: 1.67,
    vagas: 96,
    talentosInternos: 5,
    gap: 91,
    vagas1000: 19.9,
    feminino: 29,
    masculino: 71,
  },
  {
    rank: 30,
    competencia: "Gestão operacional",
    profissionais: 4680,
    pctTotal: 1.62,
    vagas: 0,
    talentosInternos: 4,
    gap: -4,
    vagas1000: 0.0,
    feminino: 38,
    masculino: 62,
  },
  {
    rank: 31,
    competencia: "Engenharia",
    profissionais: 4680,
    pctTotal: 1.62,
    vagas: 181,
    talentosInternos: 5,
    gap: 176,
    vagas1000: 38.7,
    feminino: 17,
    masculino: 83,
  },
  {
    rank: 32,
    competencia: "SQL",
    profissionais: 4635,
    pctTotal: 1.6,
    vagas: 26,
    talentosInternos: 4,
    gap: 22,
    vagas1000: 5.6,
    feminino: 15,
    masculino: 85,
  },
  {
    rank: 33,
    competencia: "5S",
    profissionais: 4547,
    pctTotal: 1.57,
    vagas: 16,
    talentosInternos: 2,
    gap: 14,
    vagas1000: 3.5,
    feminino: 26,
    masculino: 74,
  },
  {
    rank: 34,
    competencia: "Contabilidade",
    profissionais: 4388,
    pctTotal: 1.52,
    vagas: 407,
    talentosInternos: 3,
    gap: 404,
    vagas1000: 92.8,
    feminino: 48,
    masculino: 52,
  },
  {
    rank: 35,
    competencia: "Implementação de KPI",
    profissionais: 4258,
    pctTotal: 1.47,
    vagas: 0,
    talentosInternos: 3,
    gap: -3,
    vagas1000: 0.0,
    feminino: 33,
    masculino: 67,
  },
  {
    rank: 36,
    competencia: "Funções de recepcionista",
    profissionais: 4254,
    pctTotal: 1.47,
    vagas: 10,
    talentosInternos: 0,
    gap: 10,
    vagas1000: 2.4,
    feminino: 82,
    masculino: 18,
  },
  {
    rank: 37,
    competencia: "Indicadores-chave de desempenho",
    profissionais: 4253,
    pctTotal: 1.47,
    vagas: 37,
    talentosInternos: 3,
    gap: 34,
    vagas1000: 8.7,
    feminino: 34,
    masculino: 66,
  },
  {
    rank: 38,
    competencia: "Orçamento",
    profissionais: 4247,
    pctTotal: 1.47,
    vagas: 334,
    talentosInternos: 2,
    gap: 332,
    vagas1000: 78.6,
    feminino: 39,
    masculino: 61,
  },
  {
    rank: 39,
    competencia: "Arrecadação de contas a receber",
    profissionais: 4216,
    pctTotal: 1.46,
    vagas: 0,
    talentosInternos: 0,
    gap: 0,
    vagas1000: 0.0,
    feminino: 67,
    masculino: 33,
  },
  {
    rank: 40,
    competencia: "Direito civil",
    profissionais: 4143,
    pctTotal: 1.43,
    vagas: 4,
    talentosInternos: 1,
    gap: 3,
    vagas1000: 1.0,
    feminino: 54,
    masculino: 46,
  },
  {
    rank: 41,
    competencia: "Experiência do cliente",
    profissionais: 4001,
    pctTotal: 1.38,
    vagas: 67,
    talentosInternos: 1,
    gap: 66,
    vagas1000: 16.7,
    feminino: 56,
    masculino: 44,
  },
  {
    rank: 42,
    competencia: "Microsoft Project",
    profissionais: 3948,
    pctTotal: 1.36,
    vagas: 0,
    talentosInternos: 4,
    gap: -4,
    vagas1000: 0.0,
    feminino: 23,
    masculino: 77,
  },
  {
    rank: 43,
    competencia: "Marketing digital",
    profissionais: 3928,
    pctTotal: 1.36,
    vagas: 8,
    talentosInternos: 1,
    gap: 7,
    vagas1000: 2.0,
    feminino: 46,
    masculino: 54,
  },
  {
    rank: 44,
    competencia: "Satisfação do cliente",
    profissionais: 3846,
    pctTotal: 1.33,
    vagas: 480,
    talentosInternos: 0,
    gap: 480,
    vagas1000: 124.8,
    feminino: 47,
    masculino: 53,
  },
  {
    rank: 45,
    competencia: "Litígios",
    profissionais: 3761,
    pctTotal: 1.3,
    vagas: 94,
    talentosInternos: 1,
    gap: 93,
    vagas1000: 25.0,
    feminino: 53,
    masculino: 47,
  },
];

/* ===== Dados: somente tabela "Competências tech e dados" ===== */
export const competenciasTechDados = [
  {
    rank: 71,
    competencia: "JavaScript",
    profissionais: 3076,
    pctTotal: 1.06,
    vagas: 36,
    talentosInternos: 3,
    gap: 33,
    vagas1000: 11.7,
    feminino: 12,
    masculino: 88,
  },
  {
    rank: 32,
    competencia: "SQL",
    profissionais: 4635,
    pctTotal: 1.6,
    vagas: 26,
    talentosInternos: 4,
    gap: 22,
    vagas1000: 5.6,
    feminino: 15,
    masculino: 85,
  },
  {
    rank: 67,
    competencia: "Python",
    profissionais: 3189,
    pctTotal: 1.1,
    vagas: 16,
    talentosInternos: 3,
    gap: 13,
    vagas1000: 5.0,
    feminino: 15,
    masculino: 85,
  },
  {
    rank: 31,
    competencia: "Engenharia",
    profissionais: 4680,
    pctTotal: 1.62,
    vagas: 181,
    talentosInternos: 5,
    gap: 176,
    vagas1000: 38.7,
    feminino: 17,
    masculino: 83,
  },
  {
    rank: 90,
    competencia: "HTML",
    profissionais: 2763,
    pctTotal: 0.95,
    vagas: 68,
    talentosInternos: 3,
    gap: 65,
    vagas1000: 24.6,
    feminino: 18,
    masculino: 82,
  },
  {
    rank: 94,
    competencia: "Banco de dados",
    profissionais: 2743,
    pctTotal: 0.95,
    vagas: 10,
    talentosInternos: 2,
    gap: 8,
    vagas1000: 3.6,
    feminino: 19,
    masculino: 81,
  },
  {
    rank: 60,
    competencia: "Microsoft Power BI",
    profissionais: 3369,
    pctTotal: 1.16,
    vagas: 0,
    talentosInternos: 2,
    gap: -2,
    vagas1000: 0.0,
    feminino: 32,
    masculino: 68,
  },
  {
    rank: 7,
    competencia: "Sistemas operacionais",
    profissionais: 7615,
    pctTotal: 2.63,
    vagas: 70,
    talentosInternos: 7,
    gap: 63,
    vagas1000: 9.2,
    feminino: 34,
    masculino: 66,
  },
  {
    rank: 11,
    competencia: "Sistemas operacionais",
    profissionais: 7182,
    pctTotal: 2.48,
    vagas: 0,
    talentosInternos: 7,
    gap: -7,
    vagas1000: 0.0,
    feminino: 34,
    masculino: 66,
  },
  {
    rank: 2,
    competencia: "Análise de dados",
    profissionais: 13311,
    pctTotal: 4.6,
    vagas: 1,
    talentosInternos: 4,
    gap: -3,
    vagas1000: 0.1,
    feminino: 46,
    masculino: 54,
  },
];

/* ===== Dados: seção Gaps e Pressão (PDF) ===== */
export const maioresGaps = [
  {
    competencia: "Satisfação do cliente",
    vagas: 480,
    talentosInternos: 0,
    gap: 480,
    profissionais: 3846,
    pressao: 124.8,
    prioridade: "Alta",
  },
  {
    competencia: "Contabilidade",
    vagas: 407,
    talentosInternos: 3,
    gap: 404,
    profissionais: 4388,
    pressao: 92.8,
    prioridade: "Alta",
  },
  {
    competencia: "Educação",
    vagas: 389,
    talentosInternos: 6,
    gap: 383,
    profissionais: 3440,
    pressao: 113.1,
    prioridade: "Alta",
  },
  {
    competencia: "Orçamento",
    vagas: 334,
    talentosInternos: 2,
    gap: 332,
    profissionais: 4247,
    pressao: 78.6,
    prioridade: "Alta",
  },
  {
    competencia: "Finanças",
    vagas: 216,
    talentosInternos: 3,
    gap: 213,
    profissionais: 5949,
    pressao: 36.3,
    prioridade: "Média",
  },
  {
    competencia: "Engenharia",
    vagas: 181,
    talentosInternos: 5,
    gap: 176,
    profissionais: 4680,
    pressao: 38.7,
    prioridade: "Média",
  },
  {
    competencia: "Comercial",
    vagas: 159,
    talentosInternos: 1,
    gap: 158,
    profissionais: 7523,
    pressao: 21.1,
    prioridade: "Média",
  },
  {
    competencia: "Gestão de relacionamento com o cliente (CRM)",
    vagas: 157,
    talentosInternos: 0,
    gap: 157,
    profissionais: 6315,
    pressao: 24.9,
    prioridade: "Média",
  },
  {
    competencia: "Assistência médica",
    vagas: 120,
    talentosInternos: 0,
    gap: 120,
    profissionais: 2747,
    pressao: 43.7,
    prioridade: "Média",
  },
  {
    competencia: "Recursos humanos (RH)",
    vagas: 116,
    talentosInternos: 6,
    gap: 110,
    profissionais: 5452,
    pressao: 21.3,
    prioridade: "Média",
  },
  {
    competencia: "Litígios",
    vagas: 94,
    talentosInternos: 1,
    gap: 93,
    profissionais: 3761,
    pressao: 25.0,
    prioridade: "Monitorar",
  },
  {
    competencia: "ERP (Planejamento de recursos empresariais)",
    vagas: 96,
    talentosInternos: 5,
    gap: 91,
    profissionais: 4833,
    pressao: 19.9,
    prioridade: "Monitorar",
  },
  {
    competencia: "Gestão logística",
    vagas: 92,
    talentosInternos: 2,
    gap: 90,
    profissionais: 5074,
    pressao: 18.1,
    prioridade: "Monitorar",
  },
  {
    competencia: "Contas a receber",
    vagas: 81,
    talentosInternos: 0,
    gap: 81,
    profissionais: 5020,
    pressao: 16.1,
    prioridade: "Monitorar",
  },
  {
    competencia: "Serviços bancários",
    vagas: 78,
    talentosInternos: 0,
    gap: 78,
    profissionais: 2746,
    pressao: 28.4,
    prioridade: "Monitorar",
  },
  {
    competencia: "Experiência do cliente",
    vagas: 67,
    talentosInternos: 1,
    gap: 66,
    profissionais: 4001,
    pressao: 16.7,
    prioridade: "Monitorar",
  },
  {
    competencia: "Habilidades analíticas",
    vagas: 72,
    talentosInternos: 6,
    gap: 66,
    profissionais: 15214,
    pressao: 4.7,
    prioridade: "Monitorar",
  },
  {
    competencia: "HTML",
    vagas: 68,
    talentosInternos: 3,
    gap: 65,
    profissionais: 2763,
    pressao: 24.6,
    prioridade: "Monitorar",
  },
  {
    competencia: "Sistemas operacionais",
    vagas: 70,
    talentosInternos: 7,
    gap: 63,
    profissionais: 7615,
    pressao: 9.2,
    prioridade: "Monitorar",
  },
  {
    competencia: "Contas a pagar",
    vagas: 61,
    talentosInternos: 1,
    gap: 60,
    profissionais: 6889,
    pressao: 8.9,
    prioridade: "Monitorar",
  },
];

export const pressaoContratacao = [
  {
    competencia: "Satisfação do cliente",
    vagas1000: 124.8,
    vagas: 480,
    profissionais: 3846,
    talentosInternos: 0,
    leitura: "Muito alta",
  },
  {
    competencia: "Educação",
    vagas1000: 113.1,
    vagas: 389,
    profissionais: 3440,
    talentosInternos: 6,
    leitura: "Muito alta",
  },
  {
    competencia: "Contabilidade",
    vagas1000: 92.8,
    vagas: 407,
    profissionais: 4388,
    talentosInternos: 3,
    leitura: "Alta",
  },
  {
    competencia: "Orçamento",
    vagas1000: 78.6,
    vagas: 334,
    profissionais: 4247,
    talentosInternos: 2,
    leitura: "Alta",
  },
  {
    competencia: "Assistência médica",
    vagas1000: 43.7,
    vagas: 120,
    profissionais: 2747,
    talentosInternos: 0,
    leitura: "Moderada",
  },
  {
    competencia: "Engenharia",
    vagas1000: 38.7,
    vagas: 181,
    profissionais: 4680,
    talentosInternos: 5,
    leitura: "Moderada",
  },
  {
    competencia: "Finanças",
    vagas1000: 36.3,
    vagas: 216,
    profissionais: 5949,
    talentosInternos: 3,
    leitura: "Moderada",
  },
  {
    competencia: "Serviços bancários",
    vagas1000: 28.4,
    vagas: 78,
    profissionais: 2746,
    talentosInternos: 0,
    leitura: "Moderada",
  },
  {
    competencia: "Litígios",
    vagas1000: 25.0,
    vagas: 94,
    profissionais: 3761,
    talentosInternos: 1,
    leitura: "Moderada",
  },
  {
    competencia: "Gestão de relacionamento com o cliente (CRM)",
    vagas1000: 24.9,
    vagas: 157,
    profissionais: 6315,
    talentosInternos: 0,
    leitura: "Moderada",
  },
  {
    competencia: "HTML",
    vagas1000: 24.6,
    vagas: 68,
    profissionais: 2763,
    talentosInternos: 3,
    leitura: "Moderada",
  },
  {
    competencia: "Recursos humanos (RH)",
    vagas1000: 21.3,
    vagas: 116,
    profissionais: 5452,
    talentosInternos: 6,
    leitura: "Moderada",
  },
  {
    competencia: "Comercial",
    vagas1000: 21.1,
    vagas: 159,
    profissionais: 7523,
    talentosInternos: 1,
    leitura: "Moderada",
  },
  {
    competencia: "ERP (Planejamento de recursos empresariais)",
    vagas1000: 19.9,
    vagas: 96,
    profissionais: 4833,
    talentosInternos: 5,
    leitura: "Baixa",
  },
  {
    competencia: "Relatórios financeiros",
    vagas1000: 18.2,
    vagas: 52,
    profissionais: 2856,
    talentosInternos: 1,
    leitura: "Baixa",
  },
  {
    competencia: "Gestão logística",
    vagas1000: 18.1,
    vagas: 92,
    profissionais: 5074,
    talentosInternos: 2,
    leitura: "Baixa",
  },
  {
    competencia: "Experiência do cliente",
    vagas1000: 16.7,
    vagas: 67,
    profissionais: 4001,
    talentosInternos: 1,
    leitura: "Baixa",
  },
  {
    competencia: "Conciliação bancária",
    vagas1000: 16.2,
    vagas: 49,
    profissionais: 3030,
    talentosInternos: 0,
    leitura: "Baixa",
  },
  {
    competencia: "Contas a receber",
    vagas1000: 16.1,
    vagas: 81,
    profissionais: 5020,
    talentosInternos: 0,
    leitura: "Baixa",
  },
  {
    competencia: "Enfermagem",
    vagas1000: 14.3,
    vagas: 47,
    profissionais: 3296,
    talentosInternos: 0,
    leitura: "Baixa",
  },
];

/* ===== Demanda Futura ===== */
export const demandaFuturaBase = [
  { competencia: "Satisfação do cliente", valorAtual: 480, valorAnterior: 420 },
  { competencia: "Contabilidade", valorAtual: 407, valorAnterior: 360 },
  { competencia: "Educação", valorAtual: 389, valorAnterior: 340 },
  { competencia: "Orçamento", valorAtual: 334, valorAnterior: 300 },
  { competencia: "Finanças", valorAtual: 216, valorAnterior: 190 },
  { competencia: "Engenharia", valorAtual: 181, valorAnterior: 160 },
  { competencia: "Comercial", valorAtual: 159, valorAnterior: 145 },
  { competencia: "CRM", valorAtual: 157, valorAnterior: 140 },
  { competencia: "Assistência médica", valorAtual: 120, valorAnterior: 108 },
  { competencia: "Recursos humanos (RH)", valorAtual: 116, valorAnterior: 105 },
];

/* ===== Distribuição de Gênero por Competência ===== */
export const distribuicaoGeneroData = [
  {
    competencia: "JavaScript",
    profissionais: 3076,
    feminino: 12,
    masculino: 88,
    diferenca: 76,
    vagas: 36,
  },
  {
    competencia: "SQL",
    profissionais: 4635,
    feminino: 15,
    masculino: 85,
    diferenca: 70,
    vagas: 26,
  },
  {
    competencia: "Python",
    profissionais: 3189,
    feminino: 15,
    masculino: 85,
    diferenca: 70,
    vagas: 16,
  },
  {
    competencia: "Recepção telefônica",
    profissionais: 2837,
    feminino: 84,
    masculino: 16,
    diferenca: 68,
    vagas: 0,
  },
  {
    competencia: "Engenharia",
    profissionais: 4680,
    feminino: 17,
    masculino: 83,
    diferenca: 66,
    vagas: 181,
  },
  {
    competencia: "Funções de recepcionista",
    profissionais: 4254,
    feminino: 82,
    masculino: 18,
    diferenca: 64,
    vagas: 10,
  },
  {
    competencia: "HTML",
    profissionais: 2763,
    feminino: 18,
    masculino: 82,
    diferenca: 64,
    vagas: 68,
  },
  {
    competencia: "Banco de dados",
    profissionais: 2743,
    feminino: 19,
    masculino: 81,
    diferenca: 62,
    vagas: 10,
  },
  {
    competencia: "Enfermagem",
    profissionais: 3296,
    feminino: 79,
    masculino: 21,
    diferenca: 58,
    vagas: 47,
  },
  {
    competencia: "Suporte técnico",
    profissionais: 3015,
    feminino: 21,
    masculino: 79,
    diferenca: 58,
    vagas: 4,
  },
  {
    competencia: "Microsoft Project",
    profissionais: 3948,
    feminino: 23,
    masculino: 77,
    diferenca: 54,
    vagas: 0,
  },
  {
    competencia: "5S",
    profissionais: 4547,
    feminino: 26,
    masculino: 74,
    diferenca: 48,
    vagas: 16,
  },
  {
    competencia: "Gestão logística",
    profissionais: 5074,
    feminino: 27,
    masculino: 73,
    diferenca: 46,
    vagas: 92,
  },
  {
    competencia: "Desenvolvimento de novos negócios",
    profissionais: 2779,
    feminino: 27,
    masculino: 73,
    diferenca: 46,
    vagas: 0,
  },
  {
    competencia: "Ciclo PDCA",
    profissionais: 7314,
    feminino: 29,
    masculino: 71,
    diferenca: 42,
    vagas: 4,
  },
  {
    competencia: "ERP (Planejamento de recursos empresariais)",
    profissionais: 4833,
    feminino: 29,
    masculino: 71,
    diferenca: 42,
    vagas: 96,
  },
  {
    competencia: "Normas ISO",
    profissionais: 2828,
    feminino: 29,
    masculino: 71,
    diferenca: 42,
    vagas: 4,
  },
  {
    competencia: "Recursos humanos (RH)",
    profissionais: 5452,
    feminino: 69,
    masculino: 31,
    diferenca: 38,
    vagas: 116,
  },
  {
    competencia: "Representação de vendedores",
    profissionais: 3037,
    feminino: 31,
    masculino: 69,
    diferenca: 38,
    vagas: 0,
  },
  {
    competencia: "Melhoria contínua",
    profissionais: 3730,
    feminino: 32,
    masculino: 68,
    diferenca: 36,
    vagas: 3,
  },
];

/* ===== Educação e Competências Emergentes ===== */
export const eeAreasEstudo = [
  {
    area: "Data Science",
    profissionais: 483,
    recemFormados: 245,
    pctRecemFormados: 50.7,
    suasContratacoes: 0,
  },
  {
    area: "Tecnologia em Controle de Qualidade",
    profissionais: 479,
    recemFormados: 124,
    pctRecemFormados: 25.9,
    suasContratacoes: 0,
  },
];

export const eeCompetenciasEmergentes = [];

/* ===== Qualidade dos Dados ===== */
export const qdCoberturaAbas = [
  { status: "Com dados", aba: "Áreas de estudo", linhas: 2 },
  { status: "Com dados", aba: "Competências comuns", linhas: 100 },
  { status: "Metadados", aba: "Visão geral", linhas: 9 },

  { status: "Somente cabeçalho", aba: "Cargos comuns", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Cargos em crescimento", linhas: 0 },
  {
    status: "Somente cabeçalho",
    aba: "Competências em crescimento",
    linhas: 0,
  },
  { status: "Somente cabeçalho", aba: "Empresas", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Empresas não exploradas", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Formações", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Instituições de ensino", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Localidades", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Mudanças de localidades", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Mudanças de setor", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Propostas de valor", linhas: 0 },
  { status: "Somente cabeçalho", aba: "Setores", linhas: 0 },
];

export const qdDuplicidades = [
  {
    entidade: "Sistemas operacionais",
    tipo: "competencia",
    registros: 2,
    rankings: "7, 11",
    profissionaisSomados: 14797,
    vagasSomadas: 70,
    talentosSomados: 14,
  },
];

export const qdLogs = [
  {
    nivel: "alerta",
    origem: "Competências comuns",
    mensagem:
      'Campo: nome — Competência "Sistemas operacionais" aparece em mais de uma linha; a PoC preserva os registros originais.',
  },
  {
    nivel: "alerta",
    origem: "Instituições de ensino",
    mensagem: "Aba disponível apenas com cabeçalho na carga atual.",
  },
  {
    nivel: "alerta",
    origem: "Setores",
    mensagem: "Aba disponível apenas com cabeçalho na carga atual.",
  },
  {
    nivel: "alerta",
    origem: "Cargos comuns",
    mensagem: "Aba disponível apenas com cabeçalho na carga atual.",
  },
];

export const qdRoadmap = [
  {
    modulo: "Localidades",
    descricao: "Distribuição territorial dos profissionais.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Mudanças de localidades",
    descricao: "Fluxos de entrada e saída entre localidades.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Empresas",
    descricao: "Empregadores que concentram talentos.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Empresas não exploradas",
    descricao: "Oportunidades de prospecção em empresas ainda não trabalhadas.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Cargos comuns",
    descricao: "Ocupações mais frequentes.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Cargos em crescimento",
    descricao: "Tendências ocupacionais.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Competências em crescimento",
    descricao: "Competências emergentes por crescimento anual.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Setores",
    descricao: "Distribuição setorial dos talentos.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Mudanças de setor",
    descricao: "Fluxos entre setores.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Instituições de ensino",
    descricao: "Instituições formadoras.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Formações",
    descricao: "Distribuição por grau de formação.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
  {
    modulo: "Propostas de valor",
    descricao: "Atributos de EVP e consenso dos talentos.",
    status: "Somente cabeçalho",
    linhas: 0,
  },
];

/* ===== Inferências Avançadas ===== */
export const iaLacunasBase = [
  {
    competencia: "Habilidades analíticas",
    profissionais: 15214,
    vagas: 72,
    talentos: 6,
    vagas1000: 4.7,
    feminino: 46,
    masculino: 54,
  },
  {
    competencia: "Análise de dados",
    profissionais: 13311,
    vagas: 1,
    talentos: 4,
    vagas1000: 0.1,
    feminino: 46,
    masculino: 54,
  },
  {
    competencia: "Gestão de vendas",
    profissionais: 9735,
    vagas: 7,
    talentos: 1,
    vagas1000: 0.7,
    feminino: 34,
    masculino: 66,
  },
  {
    competencia: "Análise financeira",
    profissionais: 9194,
    vagas: 3,
    talentos: 4,
    vagas1000: 0.3,
    feminino: 49,
    masculino: 51,
  },
  {
    competencia: "Planejamento empresarial",
    profissionais: 8459,
    vagas: 7,
    talentos: 6,
    vagas1000: 0.8,
    feminino: 33,
    masculino: 67,
  },
];

export const iaClusterBase = [
  {
    competencia: "Habilidades analíticas",
    profissionais: 15214,
    vagas: 72,
    feminino: 46,
    masculino: 54,
  },
  {
    competencia: "Análise de dados",
    profissionais: 13311,
    vagas: 1,
    feminino: 46,
    masculino: 54,
  },
  {
    competencia: "Gestão de vendas",
    profissionais: 9735,
    vagas: 7,
    feminino: 34,
    masculino: 66,
  },
  {
    competencia: "Análise financeira",
    profissionais: 9194,
    vagas: 3,
    feminino: 49,
    masculino: 51,
  },
  {
    competencia: "Planejamento empresarial",
    profissionais: 8459,
    vagas: 7,
    feminino: 33,
    masculino: 67,
  },
  {
    competencia: "Linhas de produção",
    profissionais: 7823,
    vagas: 29,
    feminino: 38,
    masculino: 62,
  },
  {
    competencia: "Sistemas operacionais",
    profissionais: 7615,
    vagas: 70,
    feminino: 34,
    masculino: 66,
  },
  {
    competencia: "Comercial",
    profissionais: 7523,
    vagas: 159,
    feminino: 35,
    masculino: 65,
  },
  {
    competencia: "Suporte administrativo",
    profissionais: 7509,
    vagas: 17,
    feminino: 67,
    masculino: 33,
  },
  {
    competencia: "Ciclo PDCA",
    profissionais: 7314,
    vagas: 4,
    feminino: 29,
    masculino: 71,
  },
];

/* ===== Alertas e Sugestões ===== */
export const asGeneroAlerts = [
  { competencia: "Orçamento", gap: 22.0 },
  { competencia: "Melhoria de processos", gap: 22.0 },
  { competencia: "Prospecção", gap: 22.0 },
  { competencia: "Linhas de produção", gap: 24.0 },
  { competencia: "Gestão operacional", gap: 24.0 },
  { competencia: "Educação", gap: 24.0 },
  { competencia: "Controle de inventário", gap: 26.0 },
  { competencia: "Farmácia", gap: 28.0 },
  { competencia: "Reconciliações contábeis", gap: 28.0 },
  { competencia: "Comercial", gap: 30.0 },
  { competencia: "Produtos SAP", gap: 30.0 },
  {
    competencia: "Relatórios de indicadores-chave de desempenho (KPI)",
    gap: 30.0,
  },
  { competencia: "Gestão de vendas", gap: 32.0 },
  { competencia: "Sistemas operacionais", gap: 32.0 },
  { competencia: "Sistemas operacionais", gap: 32.0 },
  { competencia: "Contas a receber", gap: 32.0 },
  { competencia: "Processo de faturamento", gap: 32.0 },
  { competencia: "Indicadores-chave de desempenho", gap: 32.0 },
  { competencia: "Conciliação bancária", gap: 32.0 },
  { competencia: "Gestão comercial", gap: 32.0 },
  { competencia: "Planejamento empresarial", gap: 34.0 },
  { competencia: "Suporte administrativo", gap: 34.0 },
  { competencia: "Contas a pagar", gap: 34.0 },
  { competencia: "AutoCAD", gap: 34.0 },
  { competencia: "Implementação de KPI", gap: 34.0 },
  { competencia: "Arrecadação de contas a receber", gap: 34.0 },
  { competencia: "Melhoria contínua", gap: 36.0 },
  { competencia: "Administração de alto escalão", gap: 36.0 },
  { competencia: "Telemarketing", gap: 36.0 },
  { competencia: "Processos administrativos", gap: 36.0 },
  { competencia: "Microsoft Power BI", gap: 36.0 },
  { competencia: "Microsoft PowerApps", gap: 36.0 },
  { competencia: "Pacote Microsoft BI", gap: 36.0 },
  { competencia: "Recrutamento", gap: 36.0 },
  { competencia: "Assistência médica", gap: 36.0 },
  { competencia: "Recursos humanos (RH)", gap: 38.0 },
  { competencia: "Representação de vendedores", gap: 38.0 },
  { competencia: "Ciclo PDCA", gap: 42.0 },
  { competencia: "ERP (Planejamento de recursos empresariais)", gap: 42.0 },
  { competencia: "Normas ISO", gap: 42.0 },
  { competencia: "Gestão logística", gap: 46.0 },
  { competencia: "Desenvolvimento de novos negócios", gap: 46.0 },
  { competencia: "5S", gap: 48.0 },
  { competencia: "Microsoft Project", gap: 54.0 },
  { competencia: "Enfermagem", gap: 58.0 },
  { competencia: "Suporte técnico", gap: 58.0 },
  { competencia: "Banco de dados", gap: 62.0 },
  { competencia: "Funções de recepcionista", gap: 64.0 },
  { competencia: "HTML", gap: 64.0 },
  { competencia: "Engenharia", gap: 66.0 },
  { competencia: "Recepção telefônica", gap: 68.0 },
  { competencia: "SQL", gap: 70.0 },
  { competencia: "Python", gap: 70.0 },
  { competencia: "JavaScript", gap: 76.0 },
];

export const asDadosAlerts = [
  "Localidades",
  "Mudanças de localidades",
  "Empresas",
  "Empresas não exploradas",
  "Cargos comuns",
  "Cargos em crescimento",
  "Competências em crescimento",
  "Setores",
  "Mudanças de setor",
  "Instituições de ensino",
  "Formações",
  "Propostas de valor",
];

/* ===== Legenda das Fórmulas ===== */
export const lfFormulas = [
  {
    campo: "gap_vagas_talentos",
    formula: "(anuncios_vaga - seus_talentos)",
    interpretacao: "Gap bruto entre demanda e talentos internos mapeados.",
    tipo: "gap",
  },
  {
    campo: "vagas_por_1000_profissionais",
    formula: "((anuncios_vaga / profissionais) × 1000)",
    interpretacao: "Pressão relativa da demanda por competência.",
    tipo: "pressao",
  },
  {
    campo: "talentos_internos_pct",
    formula: "((seus_talentos / profissionais) × 100)",
    interpretacao:
      "Participação dos talentos internos no total de profissionais.",
    tipo: "kpi",
  },
  {
    campo: "desigualdade_genero_pct",
    formula: "ABS(feminino_pct - masculino_pct)",
    interpretacao: "Diferença percentual entre feminino e masculino.",
    tipo: "genero",
  },
  {
    campo: "demanda_futura",
    formula: "valor_atual + (valor_atual - valor_anterior)",
    interpretacao: "Previsão linear simples da tendência de demanda.",
    tipo: "previsao",
  },
  {
    campo: "lacunas_habilidades_pct",
    formula: "((anuncios_vaga - seus_talentos) / anuncios_vaga) × 100",
    interpretacao: "Gap percentual usado no gráfico de lacunas de habilidades.",
    tipo: "gap",
  },
];
